const {test}=require('node:test'),assert=require('node:assert/strict'),Gemini=require('../nsw-election-learning-game/src/gemini.js');
function service(fetcher){const data=new Map();return new Gemini({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)},fetcher);}
test('no key gracefully rejects without network',async()=>{const g=service(()=>{throw Error('Should not call');});assert.equal(g.isConfigured(),false);await assert.rejects(g.explain({}),/Add a key/);});
test('key persists only in injected local store and is removable',()=>{const g=service();g.save({key:'test-only-placeholder',enabled:true,model:'gemini-3.6-flash'});assert(g.isConfigured());g.save({key:'',enabled:false});assert.equal(g.config().key,'test-only-placeholder');assert(!g.isConfigured());g.remove();assert(!g.config().key);});
test('request uses header, extracts grounding, and redacts echoed key',async()=>{let request;const g=service(async(url,opts)=>{request={url,opts};return {ok:true,json:async()=>({candidates:[{content:{parts:[{text:'test-only-placeholder answer'}]},groundingMetadata:{groundingChunks:[{web:{uri:'https://www.parliament.nsw.gov.au/',title:'Parliament'}}]}}]})};});g.save({key:'test-only-placeholder',enabled:true,model:'gemini-test-flash'});const out=await g.research('Test');assert(!request.url.includes('placeholder'));assert.equal(request.opts.headers['x-goog-api-key'],'test-only-placeholder');assert(JSON.parse(request.opts.body).tools[0].google_search);assert(!out.text.includes('placeholder'));assert.equal(out.sources.length,1);});
test('invalid key and outages provide safe useful errors',async()=>{for(const status of [400,401,403,404,429,500]){const g=service(async()=>({ok:false,status}));g.save({key:'test-only-placeholder',enabled:true});await assert.rejects(g.testConnection(),e=>!e.message.includes('placeholder'));}});

const listed=(names,nextPageToken)=>({ok:true,json:async()=>({models:names.map(name=>({name:'models/'+name,supportedGenerationMethods:['generateContent']})),nextPageToken})});
const answer=()=>({ok:true,json:async()=>({candidates:[{content:{parts:[{text:'Connection successful.'}]}}]})});
test('explicit 3.8 model is tested directly without listing or switching',async()=>{const calls=[];const g=service(async(url)=>{calls.push(url);return answer();});g.save({key:'test-only-placeholder',model:'gemini-3.8-flash',enabled:false});const result=await g.testConnection();assert.equal(result.model,'gemini-3.8-flash');assert.equal(calls.length,1);assert(calls[0].endsWith('/gemini-3.8-flash:generateContent'));assert.equal(g.config().enabled,false);});
test('model discovery works independently of generation and paginates',async()=>{const g=service(async url=>url.includes('pageToken=next')?listed(['gemini-test-pro']):listed(['gemini-test-flash','gemini-test-live'],'next'));g.save({key:'test-only-placeholder',model:'gemini-3.8-flash',enabled:true});assert.deepEqual(await g.listModels(),['gemini-test-flash','gemini-test-pro']);assert.equal(g.config().model,'gemini-3.8-flash');});
test('quota diagnostic preserves Google reason and redacts key without changing model',async()=>{const g=service(async()=>({ok:false,status:429,json:async()=>({error:{message:'Free tier quota limit: 0, test-only-placeholder'}})}));g.save({key:'test-only-placeholder',model:'gemini-3.8-flash',enabled:true});await assert.rejects(g.testConnection(),e=>/HTTP 429, gemini-3.8-flash/.test(e.message)&&/limit: 0/.test(e.message)&&!e.message.includes('placeholder'));assert.equal(g.config().model,'gemini-3.8-flash');});
test('unavailable explicit model does not silently fall back',async()=>{let calls=0;const g=service(async()=>{calls++;return {ok:false,status:404};});g.save({key:'test-only-placeholder',model:'gemini-unavailable',enabled:true});await assert.rejects(g.testConnection(),/HTTP 404/);assert.equal(calls,1);assert.equal(g.config().model,'gemini-unavailable');});
test('removing the key during a connection test cannot restore it',async()=>{let g;g=service(async url=>{if(url.includes(':generateContent')){g.remove();return answer();}return listed(['gemini-test-flash']);});g.save({key:'test-only-placeholder',enabled:true});await assert.rejects(g.testConnection(),/Settings changed/);assert.equal(g.config().key,undefined);});
