const {test}=require('node:test'),assert=require('node:assert/strict'),Gemini=require('../nsw-election-learning-game/src/gemini.js');
function service(fetcher){const data=new Map();return new Gemini({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)},fetcher);}
test('no key gracefully rejects without network',async()=>{const g=service(()=>{throw Error('Should not call');});assert.equal(g.isConfigured(),false);await assert.rejects(g.explain({}),/Add a key/);});
test('key persists only in injected local store and is removable',()=>{const g=service();g.save({key:'test-only-placeholder',enabled:true,model:'gemini-3.6-flash'});assert(g.isConfigured());g.save({key:'',enabled:false});assert.equal(g.config().key,'test-only-placeholder');assert(!g.isConfigured());g.remove();assert(!g.config().key);});
test('request uses header, extracts grounding, and redacts echoed key',async()=>{let request;const g=service(async(url,opts)=>{request={url,opts};return {ok:true,json:async()=>({candidates:[{content:{parts:[{text:'test-only-placeholder answer'}]},groundingMetadata:{groundingChunks:[{web:{uri:'https://www.parliament.nsw.gov.au/',title:'Parliament'}}]}}]})};});g.save({key:'test-only-placeholder',enabled:true,model:'gemini-test-flash'});const out=await g.research('Test');assert(!request.url.includes('placeholder'));assert.equal(request.opts.headers['x-goog-api-key'],'test-only-placeholder');assert(JSON.parse(request.opts.body).tools[0].google_search);assert(!out.text.includes('placeholder'));assert.equal(out.sources.length,1);});
test('invalid key and outages provide safe useful errors',async()=>{for(const status of [400,401,403,404,429,500]){const g=service(async()=>({ok:false,status}));g.save({key:'test-only-placeholder',enabled:true});await assert.rejects(g.testConnection(),e=>!e.message.includes('placeholder'));}});

const listed=(names,nextPageToken)=>({ok:true,json:async()=>({models:names.map(name=>({name:'models/'+name,supportedGenerationMethods:['generateContent']})),nextPageToken})});
const answer=()=>({ok:true,json:async()=>({candidates:[{content:{parts:[{text:'Connection successful.'}]}}]})});
test('unavailable saved model discovers and saves a working Flash replacement',async()=>{const calls=[];const g=service(async(url,opts)=>{calls.push({url,opts});return url.includes(':generateContent')?answer():listed(['gemini-test-pro','gemini-test-flash','gemini-test-flash-image']);});g.save({key:'test-only-placeholder',model:'gemini-unavailable',enabled:false});const result=await g.testConnection();assert.equal(result.model,'gemini-test-flash');assert.match(result.text,/previous model was unavailable/);assert.equal(g.config().model,result.model);assert.equal(g.config().enabled,false);assert.equal(calls.length,2);assert(calls.every(c=>!c.url.includes('placeholder')&&c.opts.headers['x-goog-api-key']==='test-only-placeholder'));});
test('model discovery paginates, filters and preserves available saved choice',async()=>{const g=service(async url=>url.includes(':generateContent')?answer():url.includes('pageToken=next')?listed(['gemini-test-pro']):listed(['gemini-test-flash','gemini-test-live'],'next'));g.save({key:'test-only-placeholder',model:'gemini-test-pro',enabled:true});const result=await g.testConnection();assert.equal(result.model,'gemini-test-pro');assert.deepEqual(result.models,['gemini-test-flash','gemini-test-pro']);});
test('failed generation does not save a replacement and never falls back to Pro',async()=>{const g=service(async url=>url.includes(':generateContent')?{ok:false,status:429}:listed(['gemini-test-flash']));g.save({key:'test-only-placeholder',model:'gemini-old',enabled:true});await assert.rejects(g.testConnection(),/quota/);assert.equal(g.config().model,'gemini-old');assert.throws(()=>g.chooseModel(['gemini-test-pro']),/No compatible Flash/);});
test('removing the key during a connection test cannot restore it',async()=>{let g;g=service(async url=>{if(url.includes(':generateContent')){g.remove();return answer();}return listed(['gemini-test-flash']);});g.save({key:'test-only-placeholder',enabled:true});await assert.rejects(g.testConnection(),/Settings changed/);assert.equal(g.config().key,undefined);});
