/* Device-only optional service. Never included in progress exports. */
(function(root){'use strict';
const KEY='nswElectionDesk.gemini.device';
class GeminiService {
 constructor(storage,fetcher){this.storage=storage;this.fetcher=fetcher;}
 config(){try{return JSON.parse(this.storage.getItem(KEY))||{};}catch{return {};}}
 save({key,model,enabled}){const prior=this.config();this.storage.setItem(KEY,JSON.stringify({key:key||prior.key||'',model:model||prior.model||'auto',enabled:!!enabled}));}
 remove(){this.storage.removeItem(KEY);}
 isConfigured(){const c=this.config();return !!(c.key&&c.enabled);}
 async listModels(){const c=this.config();if(!c.key)throw Error('Add a key and enable AI in Settings.');
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),30000);const models=[];let token='';const seen=new Set();
 try{do{const url=new URL('https://generativelanguage.googleapis.com/v1beta/models');url.searchParams.set('pageSize','1000');if(token)url.searchParams.set('pageToken',token);const res=await this.fetcher(url.href,{headers:{'x-goog-api-key':c.key},signal:controller.signal});if(!res.ok)throw Error('Could not load models. Check your key permissions, connection and quota.');const body=await res.json();for(const m of body.models||[]){if(/^models\/gemini-[a-zA-Z0-9.-]+$/.test(m.name)&&m.supportedGenerationMethods?.includes('generateContent')&&!/image|tts|audio|live|robotics|computer-use/i.test(m.name)&&!m.name.includes(c.key))models.push(m.name.slice(7));}token=body.nextPageToken||'';if(seen.has(token))break;seen.add(token);}while(token);return [...new Set(models)];
 }catch(e){if(e.name==='AbortError')throw Error('Loading models timed out. Try again.');if(e instanceof TypeError)throw Error('Could not load models. Check your connection and key restrictions.');throw e;}finally{clearTimeout(timeout);}}
 chooseModel(models,preferred){if(models.includes(preferred))return preferred;const flash=models.filter(m=>m.includes('flash')).sort((a,b)=>Number(/preview|exp/.test(a))-Number(/preview|exp/.test(b))||b.localeCompare(a,undefined,{numeric:true}));if(!flash.length)throw Error('No compatible Flash model is available for this key. Check model access in Google AI Studio.');return flash[0];}
 async request(prompt,{grounded=false,test=false,model}={}){const c=this.config();if(!c.key||(!c.enabled&&!test))throw Error('Add a key and enable AI in Settings.');
 const selected=model||c.model||'auto';const resolved=selected==='auto'?this.chooseModel(await this.listModels()):selected;
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),30000);
 try{const res=await this.fetcher(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(resolved)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':c.key},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],...(grounded?{tools:[{google_search:{}}]}:{})}),signal:controller.signal});
 if(!res.ok)throw Error(({400:'Request rejected. Check the key, model and search support.',401:'The API key was not accepted.',403:'Key permission or restriction prevented access.',404:'Model unavailable. Choose another model.',429:'Gemini quota reached. Try again later.'})[res.status]||'Gemini is unavailable. Try again later.');
 const body=await res.json(),candidate=body.candidates?.[0];const text=(candidate?.content?.parts||[]).map(p=>p.text||'').join('\n').split(c.key).join('[redacted]');if(!text)throw Error('Gemini returned no answer. Try a different question.');
 const sources=(candidate?.groundingMetadata?.groundingChunks||[]).map(x=>x.web).filter(x=>x&&/^https:\/\//.test(x.uri)&&!x.uri.includes(c.key));return {text,sources};
 }catch(e){if(e.name==='AbortError')throw Error('Gemini timed out. Core learning is still available.');if(e instanceof TypeError)throw Error('Connection failed. Check your connection and key restrictions.');throw e;}finally{clearTimeout(timeout);}}
 async testConnection(){const before=this.config();const models=await this.listModels();const model=this.chooseModel(models,before.model);await this.request('Reply with: Connection successful.',{test:true,model});const current=this.config();if(current.key!==before.key||current.model!==before.model)throw Error('Settings changed during the test. Test again.');this.save({...current,model});return {text:`Connection successful with ${model}.`+(before.model&&before.model!=='auto'&&before.model!==model?' Your previous model was unavailable; this working Flash model is now saved.':''),sources:[],model,models};}
 explain(context,task='Explain why this fact matters and give a short memory clue.'){return this.request(`You help a politically neutral NSW state reporter learn. Use ONLY the supplied approved snapshot for factual claims. Separate inference. Do not invent facts or sources. ${task}\nApproved context: ${JSON.stringify(context)}`);}
 research(query){return this.request(`Research for a politically neutral NSW state reporter as of ${new Date().toISOString().slice(0,10)}. Prefer NSW Parliament, NSWEC and official documents; then accountability institutions and established reporting. Cite dated sources. Distinguish state districts, federal divisions and council wards. A party claim establishes only what they said. Label uncertainty and candidate status. This is temporary research, never an approved factual update. Question: ${query}`,{grounded:true});}
}
if(typeof module==='object')module.exports=GeminiService;else root.GeminiService=GeminiService;
})(typeof globalThis!=='undefined'?globalThis:this);
