#!/usr/bin/env node
/* Official-source monitor and deterministic reviewed-snapshot proposals. No AI. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..'), read=p=>JSON.parse(fs.readFileSync(p)),hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex').slice(0,16);
const GEO='https://portal.spatial.nsw.gov.au/server/rest/services/NSW_Administrative_Boundaries_Theme_multiCRS/FeatureServer/4';
const PARLIAMENT='https://www.parliament.nsw.gov.au/members-and-electorates';
const empty=(base)=>({baseVersion:base,proposedVersion:base,generatedAt:new Date().toISOString(),adds:[],updates:[],closes:[],unchangedButReverified:[],disputes:[],staleOrUnreachable:[],cardInvalidations:[],proposedCards:[]});
function compare(before,after,id){const old=new Map(before.map(r=>[r[id],r])),now=new Map(after.map(r=>[r[id],r])),out={adds:[],updates:[],closes:[],unchangedButReverified:[]};for(const [key,r]of now){if(!old.has(key))out.adds.push(r);else if(hash(old.get(key))!==hash(r))out.updates.push({id:key,before:old.get(key),after:r,priority:'P1'});else out.unchangedButReverified.push(key);}for(const [key,r]of old)if(!now.has(key))out.closes.push({id:key,before:r,priority:'P1'});return out;}
function normalizeMembers(rows,house){if(!Array.isArray(rows))throw Error('Expected complete member array');const names=new Set(),ids=new Set();const result=rows.map(r=>{if(!r||typeof r.memberId!=='string'||typeof r.name!=='string'||typeof r.party!=='string'||r.house!==house||!Array.isArray(r.office)||!Array.isArray(r.ministry))throw Error('Invalid member record');if(ids.has(r.memberId))throw Error('Duplicate member ID');ids.add(r.memberId);if(house==='Legislative Assembly'){if(typeof r.electorate!=='string'||names.has(r.electorate))throw Error('Duplicate/missing electorate');names.add(r.electorate);}return {...r,office:[...r.office].sort(),ministry:[...r.ministry].sort()};});if(result.length!==(house==='Legislative Assembly'?93:42))throw Error('Unexpected member count: investigate vacancies before proposing');return result.sort((a,b)=>a.memberId.localeCompare(b.memberId));}
async function fetchJSON(url){const r=await fetch(url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('Official endpoint HTTP '+r.status);return r.json();}
async function main(){const outputArg=process.argv.indexOf('--output'),out=path.resolve(outputArg>=0?process.argv[outputArg+1]:'refresh-output');fs.mkdirSync(out,{recursive:true});const manifest=read(path.join(ROOT,'data/manifest.json')),la=read(path.join(ROOT,'data/current-la-members.json')),lc=read(path.join(ROOT,'data/current-lc-members.json')),report=empty(hash([la,lc]));
const inputArg=process.argv.indexOf('--input');if(inputArg>=0){const proposed=read(process.argv[inputArg+1]);if(!/^\d{4}-\d{2}-\d{2}$/.test(proposed.asOf)||Date.parse(proposed.asOf)>Date.now()||proposed.source!==PARLIAMENT)throw Error('Snapshot requires an official Parliament source URL and non-future asOf');const nextLA=normalizeMembers(proposed.la,'Legislative Assembly'),nextLC=normalizeMembers(proposed.lc,'Legislative Council');if(new Set([...nextLA,...nextLC].map(r=>r.memberId)).size!==135)throw Error('Cross-house duplicate');if(nextLA.map(r=>r.electorate).sort().join('|')!==la.map(r=>r.electorate).sort().join('|'))throw Error('Seat mismatch');
for(const [name,before,after]of [['current-la-members.json',normalizeMembers(la,'Legislative Assembly'),nextLA],['current-lc-members.json',normalizeMembers(lc,'Legislative Council'),nextLC]]){const diff=compare(before,after,'memberId');for(const key of ['adds','updates','closes','unchangedButReverified'])report[key].push(...diff[key].map(value=>({dataset:name,value,asOf:proposed.asOf,source:proposed.source,verificationStatus:'single-source'})));fs.writeFileSync(path.join(out,'proposed-'+name),JSON.stringify(after,null,2)+'\n');for(const item of [...diff.updates,...diff.closes])report.cardInvalidations.push({memberId:item.id,reason:'Member, party or office changed; regenerate dependent holder/member/role cards',priority:'P1'});}
report.proposedVersion=hash([nextLA,nextLC]);
}else{
try{const attrs=await fetchJSON(GEO+'/query?where=1%3D1&outFields=districtname,cadid,modifieddate&returnGeometry=false&f=json');if(attrs.error||attrs.exceededTransferLimit||!Array.isArray(attrs.features)||attrs.features.length!==93)throw Error('Expected 93 complete official state districts');const names=attrs.features.map(f=>f.attributes.districtname).sort(),expected=read(path.join(ROOT,'data/state-electoral-districts.geojson')).features.map(f=>f.properties.districtname).sort();if(names.join('|')!==expected.join('|'))report.disputes.push({priority:'P0',source:GEO,reason:'Official state district names differ from approved geography',officialNames:names});else report.unchangedButReverified.push({dataset:'boundary district names ONLY',source:GEO,count:93});const changes=attrs.features.filter(f=>f.attributes.modifieddate&&new Date(f.attributes.modifieddate)>new Date(manifest.datasets.find(d=>d.file.includes('geojson')).retrieved+'T23:59:59Z'));if(changes.length)report.updates.push({priority:'P1',dataset:'boundary source metadata',reason:'Official records modified after snapshot; retrieve and review geometry before updating',districts:changes.map(f=>f.attributes.districtname),source:GEO});
}catch(e){report.staleOrUnreachable.push({priority:'P1',source:GEO,reason:e.message});}
try{const res=await fetch(PARLIAMENT,{signal:AbortSignal.timeout(30000)}),text=await res.text();if(!res.ok||/Just a moment|challenge-platform/.test(text))throw Error('Parliament directory access challenge or HTTP '+res.status);report.staleOrUnreachable.push({priority:'P1',source:PARLIAMENT,reason:'Directory reachable; no verified structured member adapter yet. Use reviewed official snapshot input; membership NOT reverified.'});}catch(e){report.staleOrUnreachable.push({priority:'P1',source:PARLIAMENT,reason:e.message});}
}
for(const d of manifest.datasets)if((Date.now()-Date.parse(d.retrieved))/86400000>d.maxAgeDays)report.staleOrUnreachable.push({dataset:d.file,priority:'P1',reason:'Snapshot exceeds review window',retrieved:d.retrieved});
fs.writeFileSync(path.join(out,'changes.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(out,'REVIEW.md'),`# Official-source review\n\nBase: ${report.baseVersion}; proposed: ${report.proposedVersion}.\n\n${report.adds.length} additions, ${report.updates.length} updates, ${report.closes.length} closures, ${report.disputes.length} disputes, ${report.staleOrUnreachable.length} stale/unreachable sources.\n\nNo canonical files were changed. Read changes.json and any proposed snapshots. Review P0 conflicts before P1 changes. On approval, copy the complete snapshots, update manifest retrieval metadata, rebuild and validate. Never copy a by-election or analyst figure into 2023 results.\n`);console.log('Reviewable proposal written to '+out+'; canonical data unchanged.');}
if(require.main===module)main().catch(e=>{console.error('Refresh failed: '+e.message);process.exitCode=1;});module.exports={compare,normalizeMembers,empty};
